name: CI

on:
  push:

jobs:
  style_check:
    name: style_check
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: run black
        run: |
          black .
